version: '3.6'
services:
  backtalk-postgres:
    container_name: backtalk-postgres
    image: postgres:12
    restart: always
    volumes:
    - ./db_data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  backtalk-graphql-engine:
    container_name: backtalk-graphql-engine
    image: hasura/graphql-engine:v2.1.1.cli-migrations-v3
    volumes:
      - ../hasura/migrations:/hasura-migrations
      - ../hasura/metadata:/hasura-metadata
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file:
      - .env
  backtalk-functions-service:
    container_name: backtalk-functions-service
    command: pnpm dev
    depends_on:
      - "graphql-engine"
    build:
      context: ../functions
      dockerfile: Dockerfile
    volumes:
      - ../functions/functions:/home/node/app/functions
      - ../functions/src:/home/node/app/src
    restart: always
    env_file:
        - .env