query getSurveyById($survey_id: Int!) {
  surveys_by_pk(id: $survey_id) {
    id
    is_active
    contract {
      address
      token_type
      token_ids
      chain
    }
    max_responses
    response_count
    questions {
      id
      question_type
      is_required
      options {
        id
        content
      }
    }
  }
}
