query getQuestionsBySurveyId($survey_id: Int!) {
  questions(where: { survey_id: { _eq: $survey_id } }) {
    id
    question_type
    is_required
    options {
      id
      content
    }
    survey {
      is_active
      contract {
        address
        token_type
        token_ids
        chain
      }
      max_responses
    }
    responses_aggregate {
      aggregate {
        count
      }
    }
  }
}
