query getQuestionsById($question_ids: [Int!]!) {
  questions(where: { id: { _in: $question_ids } }) {
    question_type
    options {
      id
      content
    }
    survey {
      is_active
      contract {
        address
        token_type
        token_ids
        chain
      }
      max_responses
    }
    responses_aggregate {
      aggregate {
        count
      }
    }
  }
}
